### PR TITLE
Fix local demo

### PR DESCRIPTION
**Pull request by jbearer**
* Do not set HotShot contract address. This causes the commitment task to ignore the --deploy flag and use an address which has no contract deployed
* Add healthchecks to codify startup order for native demo

### CODE REVIEW

**Comment by philippecamacho** [comment]
How can we check that the demo works properly?
I ran `just demo-native` and I get this screen:

image

**Review by sveitser — APPROVED** [review]
LGTM

**Comment by philippecamacho** [comment]
> It should look something like this:
> 

Is this normal? (Looks like the commitment task cannot start)

image


image

image

**Comment by sveitser** [comment]
@philippecamacho the logs mention something about a duplicate docker network so I would remove the docker networks (`docker network rm espresso-sequencer`) and try again.

**Comment by philippecamacho** [comment]
> docker network rm espresso-sequencer

Thanks!

**Review by philippecamacho — APPROVED** [review]
LGTM

**Pull request merged**
