### PR TITLE
[Backport release-gambit] lower priority fee for light client update 

### PR DESCRIPTION
**Pull request by alxiong**
## Description

Backport of #2148 to `release-gambit`.

### CODE REVIEW

**Comment by alxiong** [comment]
the contract CI error is weird, I can run `just sol-test` just fine locally. `error[E0463]: can't find crate for `num_enum` sounds strange.

**Comment by sveitser** [comment]
I would try erasing the github cache by bumping the cache key.

**Comment by sveitser** [comment]
@alxiong seems to have built diff-test successfully.

**Comment by alxiong** [comment]
On current `release-gambit`, "Test" job succeed, but here we seems to time out on 
`TRY 1 SLOW [>240.000s] sequencer api::sql::generic_tests::test_namespace_query`

I'm not familiar with that code. also should we fix the Slow Test and TestDemoNative failure as well?

**Comment by jbearer** [comment]
@alxiong we're not on release-gambit anymore, we're on release-rogue which forked off main recently. You can double check this change is in there

**Pull request closed without merging**
