### PR TITLE
fix typos in comments

### PR DESCRIPTION
**Pull request by GoodDaisy**

### CODE REVIEW

**Review by jbearer — APPROVED** [review]
Thanks for this @GoodDaisy! If you go ahead and sign the CLA (click the link in the comment above) I can merge this

**Comment by Ancient123** [comment]
Looks like we should turn off the static build for pull requests, the ARM build is hellishly slow without the nix cache.

**Comment by jbearer** [comment]
Yeah, we don't need to be running the static build in PRs

**Comment by GoodDaisy** [comment]
@jbearer @Ancient123 Thanks for your review.

**Pull request merged**
