### PR TITLE
fix port forwarding in docker_compose

### PR DESCRIPTION
**Pull request by jonas089**
Port forwarding seemed incorrect, all nodes were mapped to the same port.

### CODE REVIEW

**Comment by jonas089** [comment]
On a separate note:

I have noticed a "connection refused" error when trying to reach the WebServer @ port 40000. 
Could someone take a minute to explain to me in this thread how the different APIs work? Is it only possible to query a block / transaction from the Sequencer API or is it also possible to query a block / transaction through the HotShot API directly? If so, how could I query HotShot directly when running the docker image(s)?

**Comment by jbearer** [comment]
Those are the ports internal to each docker container, so it is fine that they are all the same. The first port in each pair is the host port they are mapped to, which are all different.

I guess it would be possible to get a block directly from the HotShot CDN, but it's not really recommended or intended, as the CDN is meant to be internal to consensus: it's only real role is facilitating the exchange of messages between consensus nodes. So we don't expose the CDN port in this demo. It is better to just get the block from the query service, which is meant to be public facing.

**Comment by jonas089** [comment]
But how can I run a HotShot node in isolation, submit a transaction to that HotShot node and query that Transaction? Also, is the transaction format the same for HotShot as is for the Sequencer e.g. {vm, payload}?

Would be great if you could help me better understand the differences between a HotShot node and a Sequencer Node and how they communicate with one another

**Comment by jonas089** [comment]
https://github.com/EspressoSystems/HotShot/blob/main/crates/web_server/api.toml

I am referring to this HotShot API where you can POST a transaction and query a transaction. The structure of a transaction and the context are unclear to me

**Pull request closed without merging**
