### PR TITLE
Build and push a prebuilt geth docker

### PR DESCRIPTION
**Pull request by Ancient123**

### CODE REVIEW

**Review by jbearer — APPROVED** [review]
I don't think this has any contracts deployed. Is that alright?

**Comment by Ancient123** [comment]
> I don't think this has any contracts deployed. Is that alright?

I thought that was what the genesis file being imported was for? This is just replicating the `docker-compose.yml` that is in this repo.

**Comment by jbearer** [comment]
When we run the demo locally we run `commitment-task --deploy` which deploys the contract at runtime. I believe the genesis file only has funded accounts, but no deployed contracts

**Comment by Ancient123** [comment]
or is that handled by the commitment task running like `commitment-task --deploy` ?

**Pull request closed without merging**
