### PR TITLE
Get more information out of contracts workflow

### PR DESCRIPTION
**Pull request by jbearer**

### CODE REVIEW

**Comment by sveitser** [comment]
I think we can replace the `just gen-bindings` with something this

```diff
diff --git a/justfile b/justfile
index fc48cad..9beeb87 100644
--- a/justfile
+++ b/justfile
@@ -56,8 +56,6 @@ build-docker-images:

 # generate rust bindings for contracts
 gen-bindings:
-    forge bind --crate-name contract-bindings
-    rm -rf ./contract-bindings
-    mv ./contracts/out/bindings ./contract-bindings
+    forge bind --crate-name contract-bindings --force
     cargo fmt --all
     cargo sort -g -w
```

**Comment by jbearer** [comment]
Running that locally, I still don't get the bindings changes that we're getting in GitHub

**Comment by jbearer** [comment]
`forge --version` from the GitHub runner: `forge 0.2.0 (60ec002 2023-11-01T17:49:38.998169164Z)
`forge --version` on my machine, from the nix shell: `forge 0.2.0 (ca67d15 2023-08-02T00:17:33.385314000Z)`

So somehow, even though we're using Nix in both, we're getting a different version of forge

**Comment by sveitser** [comment]
Is it the binary from the nix shell? That would be really weird.

**Comment by jbearer** [comment]
Ok I tried rebuilding my nix shell (just `direnv allow` again) and everything broke. I did recently update OSX. Gonna try reinstalling Nix

**Comment by sveitser** [comment]
Our .envrc also needs improvement. I'll fix it.

**Comment by jbearer** [comment]
Ok. I think we can still merge this PR as it only makes the contracts workflow more informative.

**Review by sveitser — APPROVED** [review]

**Comment by jbearer** [comment]
Will merge after your PR which should fix CI

**Pull request merged**
