### PR TITLE
increase timestamp tolerance to 4 seconds

### PR DESCRIPTION
**Pull request by sveitser**

### CODE REVIEW

**Comment by tbro** [comment]
Should this PR also move timestamp validation earlier?

**Comment by tbro** [comment]
> Should this PR also move timestamp validation earlier?

never mind I see that is here: https://github.com/EspressoSystems/espresso-sequencer/pull/2137

**Review by tbro — APPROVED** [review]
I don't see how this could cause any harm.

**Comment by sveitser** [comment]
I think we will just "backport" the push to the release branch that sets it to 12 seconds instead.

**Pull request closed without merging**
