### PR TITLE
check spelling in lint job

### PR DESCRIPTION
**Pull request by tbro**
Check spelling in lint job. For now I'm just cargo installing the tool. If we decide we want this we can cache that or install the binary from github. I have also not yet added configuration to guard against any false positives.

### CODE REVIEW

**Comment by sveitser** [comment]
There's also a github action: https://github.com/marketplace/actions/typos-action

**Comment by tbro** [comment]
> This sounds like something we should add to the flake.nix and add it to the pre-commit hooks in there. This gives much quicker feedback than having it only in the CI.

Yes I think there may be some value in having the errors in this PR so we can we what we are up against.

**Comment by mrain** [comment]
> This sounds like something we should add to the flake.nix and add it to the pre-commit hooks in there. This gives much quicker feedback than having it only in the CI.

Amazing, should we propagate this action to every repo?

**Comment by mrain** [comment]
> This sounds like something we should add to the flake.nix and add it to the pre-commit hooks in there. This gives much quicker feedback than having it only in the CI.

Did it for Jellyfish 🎉  https://github.com/EspressoSystems/jellyfish/pull/513/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0

**Comment by tbro** [comment]
> > This sounds like something we should add to the flake.nix and add it to the pre-commit hooks in there. This gives much quicker feedback than having it only in the CI.
> 
> Did it for Jellyfish 🎉 https://github.com/EspressoSystems/jellyfish/pull/513/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0

Cool I copied your change there back over here

**Comment by tbro** [comment]
> This sounds like something we should add to the flake.nix and add it to the pre-commit hooks in there. This gives much quicker feedback than having it only in the CI.

One issue with running from `pre-commit` is that the tool will descend into submodules. I don't see a way to prevent that at this time.

**Review by sveitser — APPROVED** [review]

**Pull request merged**
